server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: food-ordering
      auto-index-creation: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: mailsenderthroughspring
    password: ngzahqgtagkhtlht
    port: '587'